<?php

namespace App\Console\Commands;

use App\Messaging\AnalysisRequestPublisher;
use App\Messaging\RabbitMqConnection;
use Illuminate\Console\Command;
use Illuminate\Support\Str;
use PhpAmqpLib\Exception\AMQPTimeoutException;
use PhpAmqpLib\Message\AMQPMessage;
use Throwable;

/**
 * Publish an AnalysisRequest for a ticket onto the OpsPilot event bus and,
 * with --wait, block for the agent's AnalysisResult on
 * `agent.analysis.completed`.
 */
class AnalyzeTicketCommand extends Command
{
    /**
     * @var string
     */
    protected $signature = 'opspilot:analyze-ticket
        {ticketId : The OpsPilot ticket identifier}
        {--source=cli : Where the request originated}
        {--wait : Block for the agent.analysis.completed result}
        {--timeout=15 : Seconds to wait for the result when --wait is set}';

    /**
     * @var string
     */
    protected $description = 'Publish an AnalysisRequest for a ticket and optionally wait for the agent result';

    public function handle(AnalysisRequestPublisher $publisher): int
    {
        $ticketId = (string) $this->argument('ticketId');
        $source = (string) $this->option('source');
        $correlationId = (string) Str::uuid();

        $request = [
            'ticketId' => $ticketId,
            'source' => $source,
            'payload' => [
                'title' => "Demo ticket {$ticketId}",
                'body' => 'Generated by opspilot:analyze-ticket',
            ],
            'requestedAt' => now()->toIso8601String(),
            'correlationId' => $correlationId,
        ];

        $wait = (bool) $this->option('wait');

        /** @var array<string, mixed> $config */
        $config = config('opspilot.messaging');

        // When waiting, declare + bind the reply queue BEFORE publishing so the
        // fast fake driver's result cannot land before our binding exists.
        $waitConnection = null;
        $replyQueue = null;
        if ($wait) {
            $waitConnection = new RabbitMqConnection($config);
            $waitConnection->declareTopology();
            $waitChannel = $waitConnection->channel();
            [$replyQueue] = $waitChannel->queue_declare('', false, false, true, true);
            $waitChannel->queue_bind(
                (string) $replyQueue,
                (string) $config['exchange'],
                (string) $config['analysis_completed_routing_key'],
            );
        }

        try {
            $publisher->publish($request);
        } catch (Throwable $e) {
            $waitConnection?->close();
            $this->error('Failed to publish AnalysisRequest: '.$e->getMessage());

            return self::FAILURE;
        }

        $this->line((string) json_encode($request, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
        $this->info("Published AnalysisRequest to exchange '{$config['exchange']}' routingKey '{$config['analysis_routing_key']}'");
        $this->info("correlationId={$correlationId}");

        if (! $wait) {
            return self::SUCCESS;
        }

        // $waitConnection / $replyQueue were set above under the same `$wait` guard.
        $timeout = max(1, (int) $this->option('timeout'));

        return $this->awaitResult($waitConnection, (string) $replyQueue, $ticketId, $correlationId, $timeout);
    }

    /**
     * Consume the temporary reply queue until the matching AnalysisResult
     * arrives or the timeout elapses.
     */
    private function awaitResult(
        RabbitMqConnection $connection,
        string $replyQueue,
        string $ticketId,
        string $correlationId,
        int $timeout,
    ): int {
        try {
            $channel = $connection->channel();

            /** @var array<string, mixed>|null $result */
            $result = null;

            $channel->basic_consume(
                $replyQueue,
                '',
                false,
                true,
                false,
                false,
                function (AMQPMessage $message) use (&$result, $ticketId, $correlationId): void {
                    /** @var mixed $body */
                    $body = json_decode($message->getBody(), true);
                    if (! is_array($body)) {
                        return;
                    }

                    $messageCorrelation = $message->get_properties()['correlation_id'] ?? null;
                    $bodyCorrelation = $body['correlationId'] ?? null;
                    $correlationMatches = $messageCorrelation === $correlationId || $bodyCorrelation === $correlationId;

                    if (($body['ticketId'] ?? null) === $ticketId && $correlationMatches) {
                        /** @var array<string, mixed> $body */
                        $result = $body;
                    }
                },
            );

            $deadline = microtime(true) + $timeout;
            while ($result === null && microtime(true) < $deadline) {
                try {
                    $channel->wait(null, false, max(0.5, $deadline - microtime(true)));
                } catch (AMQPTimeoutException) {
                    break;
                }
            }

            if ($result === null) {
                $this->error('RESULT_TIMEOUT');

                return self::FAILURE;
            }

            $this->line((string) json_encode($result, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
            $this->info('RESULT_OK');

            return self::SUCCESS;
        } finally {
            $connection->close();
        }
    }
}
