<?php

use App\Messaging\AnalysisRequestPublisher;
use App\Messaging\RabbitMqConnection;

/**
 * These tests exercise the pure payload-building / validation surface of the
 * publisher. They never open a RabbitMQ connection (the wrapper is lazy), so the
 * suite stays green offline.
 */
function makePublisher(): AnalysisRequestPublisher
{
    /** @var array<string, mixed> $config */
    $config = config('opspilot.messaging');

    return new AnalysisRequestPublisher(new RabbitMqConnection($config), $config);
}

it('builds a valid JSON payload for a well-formed AnalysisRequest', function () {
    $request = [
        'ticketId' => 'T-1001',
        'source' => 'cli',
        'payload' => ['title' => 'Demo ticket T-1001', 'body' => 'Generated by opspilot:analyze-ticket'],
        'requestedAt' => '2026-09-09T12:00:00+00:00',
        'correlationId' => '11111111-2222-3333-4444-555555555555',
    ];

    $json = makePublisher()->encode($request);

    expect($json)->toBeString()
        ->and($json)->not->toContain('\/')            // JSON_UNESCAPED_SLASHES
        ->and(json_decode($json, true))->toEqual($request);
});

it('rejects a malformed AnalysisRequest', function (array $bad) {
    expect(fn () => makePublisher()->encode($bad))
        ->toThrow(InvalidArgumentException::class);
})->with([
    'missing ticketId' => [['payload' => [], 'requestedAt' => '2026-09-09T12:00:00Z']],
    'empty ticketId' => [['ticketId' => '', 'payload' => [], 'requestedAt' => '2026-09-09T12:00:00Z']],
    'payload not an array' => [['ticketId' => 'T-1', 'payload' => 'nope', 'requestedAt' => '2026-09-09T12:00:00Z']],
    'missing payload' => [['ticketId' => 'T-1', 'requestedAt' => '2026-09-09T12:00:00Z']],
    'requestedAt not a date' => [['ticketId' => 'T-1', 'payload' => [], 'requestedAt' => 'not-a-date']],
    'requestedAt missing' => [['ticketId' => 'T-1', 'payload' => []]],
]);
